[package]
name = "ampsc"
version = "0.1.0"
edition = "2021"

[dependencies]
atomiclock_async = {git = "ssh://gitea@gitea.mermaid-gecko.ts.net/Metropolis/atomiclock_async.git"}
with_waker = {git = "ssh://gitea@gitea.mermaid-gecko.ts.net/Metropolis/with_waker.git"}
dlog = {git = "ssh://gitea@gitea.mermaid-gecko.ts.net/Metropolis/dlog.git"}
async-drop = {git = "ssh://gitea@gitea.mermaid-gecko.ts.net/Metropolis/async_drop.git"}
poll_escape = {git = "ssh://gitea@gitea.mermaid-gecko.ts.net/Metropolis/poll_escape.git"}
thiserror = "*"

[dev-dependencies]
afut = {git = "ssh://gitea@gitea.mermaid-gecko.ts.net/Metropolis/afut.git"}